lenguaje: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  api_key: 58b62f1a-2c6c-4c10-bed0-d47aa2a7deba
  app: suculentagram-backend
  on:
    repo: KrlosAren/suculentagram-backend
